logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    preferIpAddress: true
server:
  port: 8181   # Select any available port if neither port nor server port are specified
spring:
  datasource:
    password: 12345678
    testWhileIdle: true
    url: jdbc:mysql://35.224.186.172:3306/cargasdb?useSSL=false
    username: meltsandev
    validationQuery: SELECT 1
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: 'false'
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
file:
  container: /Users/luisarriaga/Documents/Meltsan/FileContainer/
path:
  services:
    catalog: http://kubernetes.meltsan.us/v1/
    validacion: http://130.211.126.58:8181/
    duplicados: http://35.239.173.168:8181/
    reporte: http://35.232.160.182:8181/
prod: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
